
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

namespace MiniIT.Snipe
{
	public class SnipeCommunicatorRequest : AbstractCommunicatorRequest
	{
		public bool WaitingForRoomJoined { get; private set; } = false;

		private ILogger _logger;
		private readonly ISnipeServices _services;

		private readonly AuthSubsystem _authSubsystem;

		public SnipeCommunicatorRequest(ISnipeCommunicator communicator,
			ISnipeServices services,
			AuthSubsystem authSubsystem,
			string messageType = null,
			IDictionary<string, object> data = null)
			: base(communicator, services, messageType, data)
		{
			if (services == null)
			{
				throw new ArgumentNullException(nameof(services));
			}

			_services = services;
			_authSubsystem = authSubsystem;
		}

		protected override bool CheckCommunicatorValid()
		{
			return !(_communicator == null || _communicator.RoomJoined == false && MessageType == SnipeMessageTypes.ROOM_LEAVE);
		}

		protected override bool CheckCommunicatorReady()
		{
			return _communicator.LoggedIn;
		}

		protected override void OnCommunicatorReady()
		{
			if (_communicator.RoomJoined != true &&
				MessageType.StartsWith(SnipeMessageTypes.PREFIX_ROOM) &&
				MessageType != SnipeMessageTypes.ROOM_JOIN &&
				MessageType != SnipeMessageTypes.ROOM_LEAVE)
			{
				WaitingForRoomJoined = true;
			}

			SubscribeDisconnectionEvents();

			if ((_callback != null || WaitingForRoomJoined) && MessageType != SnipeMessageTypes.ROOM_LEAVE)
			{
				_waitingForResponse = true;
				_communicator.MessageReceived -= OnMessageReceived;
				_communicator.MessageReceived += OnMessageReceived;
			}

			if (!WaitingForRoomJoined)
			{
				DoSendRequest();
			}
		}

		protected override void OnWillReconnect()
		{
			SubscribeDisconnectionEvents();

			_communicator.ConnectionEstablished -= OnCommunicatorReady;
			_authSubsystem.LoginSucceeded -= OnLoginSucceeded;
			_communicator.MessageReceived -= OnMessageReceived;

			if (_communicator.AllowRequestsToWaitForLogin)
			{
				string dataJson = Data != null ? JsonUtility.ToJson(Data) : null;
				GetLogger().LogTrace($"Waiting for login - {MessageType} - {dataJson}");

				_authSubsystem.LoginSucceeded += OnLoginSucceeded;
			}
			else
			{
				InvokeCallback(SnipeErrorCodes.NOT_READY, EMPTY_DATA);
			}
		}

		protected override void OnLoginSucceeded(int userId)
		{
			_authSubsystem.LoginSucceeded -= OnLoginSucceeded;
			base.OnLoginSucceeded(userId);
		}

		protected override void OnMessageReceived(string messageType, string errorCode, IDictionary<string, object> responseData, int requestID)
		{
			if (_communicator == null)
				return;

			if (WaitingForRoomJoined && _communicator.RoomJoined == true)
			{
				GetLogger().LogTrace($"OnMessageReceived - Room joined. Send {MessageType}, id = {GetRequestId()}");

				WaitingForRoomJoined = false;
				DoSendRequest();
				return;
			}

			base.OnMessageReceived(messageType, errorCode, responseData, requestID);
		}

		public override void Dispose()
		{
			_authSubsystem.LoginSucceeded -= OnLoginSucceeded;
			base.Dispose();
		}

		public override bool Equals(object obj) => obj is SnipeCommunicatorRequest && base.Equals(obj);

		public override int GetHashCode()
		{
			// Autogenerated
			int hashCode = -1395135913;
			hashCode = hashCode * -1521134295 + base.GetHashCode();
			return hashCode;
		}

		private ILogger GetLogger()
		{
			_logger ??= _services.LoggerFactory.CreateLogger(nameof(SnipeCommunicatorRequest));
			return _logger;
		}
	}
}
