
using System.Collections.Generic;

namespace MiniIT.Snipe
{
	public class UnauthorizedRequest : AbstractCommunicatorRequest
	{
		public UnauthorizedRequest(SnipeCommunicator communicator, ISnipeServices services, string messageType = null, IDictionary<string, object> data = null)
			: base(communicator, services, messageType, data)
		{
		}

		public override bool Equals(object obj) => obj is UnauthorizedRequest && base.Equals(obj);

		public override int GetHashCode()
		{
			// Autogenerated
			int hashCode = -1395135913;
			hashCode = hashCode * -1521134295 + base.GetHashCode();
			return hashCode;
		}
	}
}
